# Generated by Django 4.2.4 on 2024-01-06 17:15

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import galaxy.timeformatfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
            options={
                'db_table': 'galaxy_allowedip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllowedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.IntegerField(null=True)),
                ('module_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'galaxy_allowedmodule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=17, null=True)),
            ],
            options={
                'db_table': 'galaxy_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'galaxy_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'galaxy_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'galaxy_custom_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'galaxy_custom_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=17, null=True)),
            ],
            options={
                'db_table': 'galaxy_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Com_Regm', models.FileField(blank=True, null=True, upload_to='file_uploads/', verbose_name='Upload Commercial registration :')),
                ('Tax_Reg', models.FileField(blank=True, null=True, upload_to='file_uploads/', verbose_name='Upload the Tax registration :')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='Upload the Logo :')),
                ('Report_B', models.ImageField(blank=True, null=True, upload_to='reports_b/', verbose_name='Upload Reports & Letters Bottom :')),
                ('Report_H', models.ImageField(blank=True, null=True, upload_to='reports_h/', verbose_name='Upload Reports & Letters Header :')),
                ('OrganizationName', models.CharField(max_length=50, null=True, verbose_name='Organization Name :')),
                ('OrganizationEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address :')),
                ('Cost_Method', models.IntegerField(blank=True, choices=[(1, 'Weighted average'), (2, 'In first - Out first')], null=True, verbose_name='Calculate item cost as :')),
                ('Create_Receive', models.BooleanField(default=False)),
                ('Create_Issue', models.BooleanField(default=False)),
                ('Terms', models.TextField(blank=True, null=True, verbose_name='Default Terms and Conditions :')),
                ('WebsiteLink', models.URLField(blank=True, null=True)),
                ('WhatsappLink', models.URLField(blank=True, null=True)),
                ('FacebookLink', models.URLField(blank=True, null=True)),
                ('InstagramLink', models.URLField(blank=True, null=True)),
                ('CreatedDate', models.DateField(null=True, verbose_name='Created Date')),
            ],
            options={
                'db_table': 'galaxy_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'galaxy_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store_Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'galaxy_store_tax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('Psw_Flag', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('Gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('Telephone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ip_restricted', models.BooleanField(default=False)),
                ('system_user_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'galaxy_user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Taxes_Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_title', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_include', models.BooleanField()),
                ('default', models.BooleanField()),
                ('disable', models.BooleanField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_type', models.IntegerField(choices=[(1, 'On the net total of the item'), (2, 'On Previous Row Amount'), (3, 'On Previous Row Total')], null=True)),
                ('tax_amount', models.IntegerField(choices=[(4, 'Fixed Amount'), (5, 'Rate'), (6, 'Fixed Amount + Rate'), (7, 'Enter the rate manualy')], null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'galaxy_taxes_charges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('start_time', galaxy.timeformatfield.TimeFormatField(max_length=12)),
                ('end_time', galaxy.timeformatfield.TimeFormatField(max_length=12)),
            ],
            options={
                'db_table': 'galaxy_timerestriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserTypeCode', models.IntegerField(null=True)),
                ('UserTypeName', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'galaxy_userstype',
                'managed': False,
            },
        ),
    ]
