# Generated by Django 4.2.4 on 2023-08-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0015_hezar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hezar',
        ),
    ]
