# Generated by Django 4.2.4 on 2023-08-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0041_remove_subscription_code_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Com_Regm',
            field=models.FileField(null=True, upload_to='file_uploads/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Cost_Method',
            field=models.CharField(choices=[(1, 'Weighted average'), (2, 'In first-Out first')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Create_Issue',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Create_Receive',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Logo',
            field=models.ImageField(null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Org_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Report_B',
            field=models.ImageField(null=True, upload_to='reports_b/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Report_H',
            field=models.ImageField(null=True, upload_to='reports_h/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='SubscriptionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.subscription'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Tax_Reg',
            field=models.FileField(null=True, upload_to='file_uploads/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Terms',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Bundle_T',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Add-Ons', 'Add-Ons')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Bundle_T',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Add-Ons', 'Add-Ons')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Bundle_T',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Add-Ons', 'Add-Ons')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.currency'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.tax'),
        ),
    ]
