# Generated by Django 4.2.4 on 2023-09-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0055_alter_organization_facebooklink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='InstgramLink',
            new_name='InstagramLink',
        ),
    ]
