# Generated by Django 4.2.4 on 2023-09-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0061_language_user_birth_date_user_gender_user_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SubscriptionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.userstype'),
        ),
    ]
