# Generated by Django 4.2.4 on 2023-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_test_ekhtbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialname', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
            ],
        ),
    ]
