# Generated by Django 4.2.4 on 2023-08-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_trial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ekhtbar',
        ),
        migrations.DeleteModel(
            name='trial',
        ),
    ]
