# Generated by Django 4.2.4 on 2023-08-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapp',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
