# Generated by Django 4.2.4 on 2023-08-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_delete_duptest'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
        ),
    ]
