# Generated by Django 4.2.4 on 2023-08-21 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
