"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""


import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm0f_ld%t!u&@$h&@_jn%qpcr7qtmb+0t__393(9#4dp3(f!!-f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'galaxy.apps.GalaxyConfig',
    'App.apps.AppConfig',
    'mssql',

]

AUTH_USER_MODEL = 'galaxy.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

#-------------------------------------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    
    'default': {
            'ENGINE': 'mssql',
            'NAME': 'Users' ,
            'USER': 'sa',
            'PASSWORD': 'Ka@12?34#',
            'HOST': 'DESKTOP-F9VA3BH\SQLEXPRESS',
            'PORT': '',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
    },
    
}

    
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# from galaxy.models import User

def get_user_database_name(username):
    # Retrieve the user-specific database name from the User model or any other relevant model
    # You might need to customize this based on your specific implementation
    return username

def switch_to_user_database(username):
    # Retrieve the user-specific database name
    db_name = get_user_database_name(username)

    # Update the Django default database configuration dynamically
    DATABASES['default']['NAME'] = db_name

# DATABASE_CONNECTION_POOLING = False
#----------------------------------------------------------------------------------------------------------
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR + '/static/',
    # "/var/www/static/",
]

MEDIA_URL = '/files_images/'

MEDIA_ROOT = BASE_DIR + '/static/files_images'


#SMTP Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'karimraoufm@gmail.com'
EMAIL_HOST_PASSWORD = 'arcbastlomavsahf' 



# DATABASE_ROUTERS = [
#     'routers.db_routers.GalaxyRouter',
#     'routers.db_routers.AppRouter',
# ]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 

# TIME_ZONE = 'Africa/Cairo'