# Generated by Django 4.2.4 on 2024-01-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_remove_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersType',
        ),
    ]
