# Generated by Django 2.1.15 on 2023-08-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0007_auto_20230817_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usee',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
