# Generated by Django 2.1.15 on 2023-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0008_user_usee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kk',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
