# Generated by Django 2.1.15 on 2023-08-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0011_user_ali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ali',
        ),
    ]
