# Generated by Django 4.2.4 on 2023-08-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0017_duptest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DupTest',
        ),
    ]
