# Generated by Django 4.2.4 on 2023-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0018_delete_duptest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(default=0)),
                ('Balanace', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreditLimit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(default=0)),
                ('Status', models.BooleanField()),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
                ('PlanID', models.IntegerField(default=0)),
                ('AutoRenew', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
