# Generated by Django 4.2.4 on 2023-08-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0020_alter_subscription_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
