# Generated by Django 4.2.4 on 2023-08-24 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0021_alter_account_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='PlanID',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
