# Generated by Django 4.2.4 on 2023-08-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0023_organization_subscription_organizationid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='UserId',
            new_name='UserID',
        ),
        migrations.AddField(
            model_name='user',
            name='OrganizationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.organization'),
        ),
    ]
