# Generated by Django 4.2.4 on 2023-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0026_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Anually', 'Anually')], max_length=20, null=True),
        ),
    ]
