# Generated by Django 4.2.4 on 2023-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0027_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Anually', 'Anually')], max_length=20, null=True),
        ),
    ]
