# Generated by Django 4.2.4 on 2023-08-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0029_alter_cart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.product'),
        ),
    ]
