# Generated by Django 4.2.4 on 2023-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0035_remove_cart_product_remove_product_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=20, null=True),
        ),
    ]
