# Generated by Django 4.2.4 on 2023-08-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0037_remove_subscription_organizationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=20, null=True),
        ),
    ]
