# Generated by Django 4.2.4 on 2023-08-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0038_alter_cart_type_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Bundle_T',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Add-Ones', 'Add-Ones')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Bundle_T',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Add-Ones', 'Add-Ones')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Bundle_T',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Add-Ones', 'Add-Ones')], max_length=20, null=True),
        ),
    ]
