# Generated by Django 4.2.4 on 2023-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0040_subscription_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Code',
        ),
        migrations.AddField(
            model_name='product',
            name='Code',
            field=models.IntegerField(null=True),
        ),
    ]
