# Generated by Django 4.2.4 on 2023-08-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0044_alter_user_organizationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='OrganizationID',
        ),
    ]
