# Generated by Django 4.2.4 on 2023-08-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0046_remove_organization_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Cost_Method',
            field=models.CharField(choices=[(1, 'Weighted average'), (2, 'In first - Out first')], max_length=50, null=True),
        ),
    ]
