# Generated by Django 4.2.4 on 2023-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0047_alter_organization_cost_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='CreatedDate',
            field=models.DateField(null=True, verbose_name='Created Date'),
        ),
    ]
