# Generated by Django 4.2.4 on 2023-09-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0048_alter_organization_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Address',
            field=models.CharField(max_length=100, null=True, verbose_name='Address :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Com_Regm',
            field=models.FileField(null=True, upload_to='file_uploads/', verbose_name='Upload Commercial registration :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Cost_Method',
            field=models.IntegerField(choices=[(1, 'Weighted average'), (2, 'In first - Out first')], null=True, verbose_name='Calculate item cost as :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.country', verbose_name='Country :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Create_Issue',
            field=models.BooleanField(null=True, verbose_name='Automaticlly create inter-store issue inventory orders :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Create_Receive',
            field=models.BooleanField(null=True, verbose_name='Automaticlly create inter-store receive inventory orders :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.currency', verbose_name='Currency :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Logo',
            field=models.ImageField(null=True, upload_to='org_logos/', verbose_name='Upload the Logo :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OrganizationName',
            field=models.CharField(max_length=50, null=True, verbose_name='Organization Name :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Report_B',
            field=models.ImageField(null=True, upload_to='reports_b/', verbose_name='Upload Reports & Letters Bottom :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Report_H',
            field=models.ImageField(null=True, upload_to='reports_h/', verbose_name='Upload Reports & Letters Header :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.tax', verbose_name='Tax :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Tax_Reg',
            field=models.FileField(null=True, upload_to='file_uploads/', verbose_name='Upload the Tax registration :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Terms',
            field=models.TextField(null=True, verbose_name='Default Terms and Conditions :'),
        ),
    ]
