# Generated by Django 4.2.4 on 2023-09-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0050_alter_organization_create_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Com_Regm',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/', verbose_name='Upload Commercial registration :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Cost_Method',
            field=models.IntegerField(blank=True, choices=[(1, 'Weighted average'), (2, 'In first - Out first')], null=True, verbose_name='Calculate item cost as :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.country', verbose_name='Country :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.currency', verbose_name='Currency :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='Upload the Logo :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Report_B',
            field=models.ImageField(blank=True, null=True, upload_to='reports_b/', verbose_name='Upload Reports & Letters Bottom :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Report_H',
            field=models.ImageField(blank=True, null=True, upload_to='reports_h/', verbose_name='Upload Reports & Letters Header :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.tax', verbose_name='Tax :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Tax_Reg',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/', verbose_name='Upload the Tax registration :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Terms',
            field=models.TextField(blank=True, null=True, verbose_name='Default Terms and Conditions :'),
        ),
    ]
