# Generated by Django 4.2.4 on 2023-09-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0052_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='EndDate',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='StartDate',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
