# Generated by Django 4.2.4 on 2023-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0053_alter_subscription_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserTypeCode', models.IntegerField(null=True)),
                ('UserTypeName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='FacebookLink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='InstgramLink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='OrganizationEmail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='WebsiteLink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='WhatsappLink',
            field=models.URLField(null=True),
        ),
    ]
