# Generated by Django 4.2.4 on 2023-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0054_userstype_organization_facebooklink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='FacebookLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='InstgramLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OrganizationEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='WebsiteLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='WhatsappLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
