# Generated by Django 4.2.4 on 2023-09-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0058_user_subscriptionid_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Create_Issue',
            field=models.BooleanField(default=False, verbose_name='Automaticlly create inter-store issue inventory orders :'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Create_Receive',
            field=models.BooleanField(default=False, verbose_name='Automaticlly create inter-store receive inventory orders :'),
        ),
    ]
