# Generated by Django 4.2.4 on 2023-09-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0059_alter_organization_create_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.userstype'),
        ),
    ]
