# Generated by Django 4.2.4 on 2023-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0062_alter_user_language_alter_user_subscriptionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
