# Generated by Django 4.2.4 on 2023-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0063_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
