# Generated by Django 4.2.4 on 2023-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0066_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Change Avatar'),
        ),
    ]
