# Generated by Django 4.2.4 on 2023-09-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0072_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Psw_Flag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OrganizationName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Name :'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.userstype'),
        ),
    ]
