# Generated by Django 4.2.4 on 2023-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0075_promocode_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
