# Generated by Django 4.2.4 on 2023-12-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0089_alter_user_subscriptionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='Tax',
        ),
    ]
