# Generated by Django 4.2.4 on 2023-12-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0090_remove_organization_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Taxes_Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_title', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_include', models.BooleanField()),
                ('default', models.BooleanField()),
                ('disable', models.BooleanField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_type', models.IntegerField(choices=[(1, 'On the net total of the item'), (2, 'On Previous Row Amount'), (3, 'On Previous Row Total')], null=True)),
                ('tax_amount', models.IntegerField(choices=[(1, 'Fixed Amount'), (2, 'Rate'), (3, 'Fixed Amount + Rate'), (4, 'Enter the rate manualy')], null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.AddField(
            model_name='store_tax',
            name='tax_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.taxes_charges'),
        ),
    ]
