# Generated by Django 4.2.4 on 2023-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0091_store_tax_taxes_charges_delete_tax_store_tax_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_user_active',
            field=models.BooleanField(default=True),
        ),
    ]
