# Generated by Django 4.2.4 on 2023-12-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0093_store_store_tax_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taxes_charges',
            name='tax_amount',
            field=models.IntegerField(choices=[(4, 'Fixed Amount'), (5, 'Rate'), (6, 'Fixed Amount + Rate'), (7, 'Enter the rate manualy')], null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.department')),
            ],
        ),
    ]
