# Generated by Django 4.2.4 on 2023-12-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0094_department_alter_taxes_charges_tax_amount_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.organization'),
        ),
    ]
